export enum CalendarActionTypes {
    LOGIN_PAGE = "LOGIN_PAGE",
    SIGNUP_PAGE = "SIGNUP_PAGE",
    EVENTS_PAGE = "EVENTS_PAGE",
    NEW_MSG = "NEW_MSG",
    CLOSE_SNACKBAR = "CLOSE_SNACKBAR",

    REGISTER_USER = "REGISTER_USER",
    REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE",

    LOGIN = "LOGIN",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",

    GET_EVENTS = "GET_EVENTS",
    GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS",
    GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE",


    CREATE_EVENT = "CREATE_EVENT",
    CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS",
    CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE",

}
