export enum CalendarActionTypes {
    LOGIN_PAGE = "LOGIN_PAGE",
    SIGNUP_PAGE = "SIGNUP_PAGE",
    EVENTS_PAGE = "EVENTS_PAGE",
    NEW_MSG = "NEW_MSG",
    CLOSE_SNACKBAR = "CLOSE_SNACKBAR",

    REGISTER_USER = "REGISTER_USER",
    REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE",

    LOGIN = "LOGIN",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",

    LOGOUT = "LOGOUT",

    
    GET_EVENTS = "GET_EVENTS",
    GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS",
    GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE",


    CREATE_EVENT = "CREATE_EVENT",
    CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS",
    CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE",


    GET_USERS_EMAIL = "GET_USERS_EMAIL",
    GET_USERS_EMAIL_SUCCESS = "GET_USERS_EMAIL_SUCCESS",
    GET_USERS_EMAIL_FAILURE = "GET_USERS_EMAIL_FAILURE",


    UPDATE_EVENT = "UPDATE_EVENT",
    UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS",
    UPDATE_EVENT_FAILURE = "UPDATE_EVENT_FAILURE",

    DELETE_EVENT = "DELETE_EVENT",
    DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS",
    DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE",

    ACCEPT_EVENT = "ACCEPT_EVENT",
    ACCEPT_EVENT_SUCCESS = "ACCEPT_EVENT_SUCCESS",
    ACCEPT_EVENT_FAILURE = "ACCEPT_EVENT_FAILURE",

    REFUSE_EVENT = "REFUSE_EVENT",
    REFUSE_EVENT_SUCCESS = "REFUSE_EVENT_SUCCESS",
    REFUSE_EVENT_FAILURE = "REFUSE_EVENT_FAILURE"


}
